// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK1ZG_B0hS6mLS6jeF55mB_DtLMSU9NiA',
    appId: '1:490375119314:web:5591c97990891ce96f080b',
    messagingSenderId: '490375119314',
    projectId: 'proservapp-a57b9',
    authDomain: 'proservapp-a57b9.firebaseapp.com',
    storageBucket: 'proservapp-a57b9.firebasestorage.app',
    measurementId: 'G-G0T028HLRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJnD4RYpPsBsEFp7FWqXVaAV4s-0lScRA',
    appId: '1:490375119314:android:cc6a59b73f298df26f080b',
    messagingSenderId: '490375119314',
    projectId: 'proservapp-a57b9',
    storageBucket: 'proservapp-a57b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVS_vPjOqCaWq4d-TdNvEDt1Y4Pyz_WRA',
    appId: '1:490375119314:ios:8a4fe20672b17b856f080b',
    messagingSenderId: '490375119314',
    projectId: 'proservapp-a57b9',
    storageBucket: 'proservapp-a57b9.firebasestorage.app',
    iosBundleId: 'com.example.agri',
  );
}
